# .github/workflows/publish-to-pypi.yml
on:
  push:
    branches:
      - main
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/legitindicators
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine
      - name: Build distribution
        run: |
          ls -lart
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
